### ISSUE TITLE
Not compatible with query hash

### ISSUE THREAD

**Issue by patric-eberle** [mistakster/postcss-pipeline-webpack-plugin#30]
If I use the build hash as a query param (e.g. `app.css?123456`) by defining `[name].css?[contenthash]` in the webpack configuration, postcss-pipeline isn't able to find the output file. If I remove the hash, the build is working as expected.

**Comment by mistakster** [comment]
Hi Patric!

As I understood your problem correctly, you use `[name].css?[contenthash]` as a template for the file name. I bet query params are useless here because file name can’t contain query param, right? You will get just `app.css` (for example) on your disk in any case.

At the same time, webpack keeps generated file name as is internally and it doesn’t match `/\.css$/`. That’s why your pipeline is not working as expected.

My advice is not to use query param.

Please, let me know if I miss something and you need such template. It would be nice if you can provide webpack.config.js to reproduce your case.

**Comment by patric-eberle** [comment]
Hi @mistakster - True, the filename is without the contenthash. But the hash is injected into the index.html by `HtmlWebpackPlugin`. This way I'm able to use the same file names for each build, while still having a custom source link. This was initially due the fact, that we use the build for different environments. But since I had the same problem with an other package I probably will have to switch to a solution without query hash.

You can find an example configuration [here](https://github.com/patric-eberle/vue-template/blob/feature/criticalcss/webpack.config.js).

**Comment by mistakster** [comment]
Thanks for rising the issue.

Yeah, you are right. I forgot about `HtmlWebpackPlugin`. We use it in our projects too, but our template is `[name].[contenthash].css`, so we didn’t face this issue before. 

I’ll work it out ASAP and let you know then.

**Comment by mistakster** [comment]
Hi @patric-eberle 

I’ve just published a new version (3.1.0) with relevant patch. Hope it will work for you whether you decided to use query params or not. 

Thank you for your help.

**Comment by patric-eberle** [comment]
Made a test run and it looks like it's working now. THX!
